trainingssets:
    - /home/peter/mount/data/fold0_MSSM_HWW_trainingsset.root
    - /home/peter/mount/data/fold1_MSSM_HWW_trainingsset.root

class_weights:
    hww120_300: 1.0
    hww350_750: 1.0
    hww800_3000: 10.0
    DY: 1.0
    WW: 1.0
    VVV: 1.0
    DiBoson: 1.0
    WJets: 1.0
    Top: 1.0

classes:
    - hww120_300
    - hww350_750
    - hww800_3000
    - DY
    - WW
    - VVV
    - DiBoson
    - WJets
    - Top

output_path: /home/peter/mount/data

global_weight: 1.

event_weights: training_weight

#features = training variables
features:
    - detajj
    - dphilep1jet1
    - dphilep1jet2
    - dphilep2jet1
    - dphilep2jet2
    - dphill
    - dphilmet
    - dphilmet1
    - dphilmet2
    - jeteta1
    - jeteta2
    - jetmass1
    - jetmass2
    - mjj
    - mll
    - mth
    - mtw1
    - mtw2
    - nbjet
    - njet
    - pTWW
    - ptll
    - dphijet1met
    - dphijet2met
    - jetpt1
    - jetpt2

train_test_split: 0.75

#trainings_weight_file: "MSSM_training/weights/TMVAmulticlassification_PyKeras_MSSM_HWW.weights.xml"
